
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

init: ## enable each project to have its own virtual environment by prefer-active-python=true & in-project=true
	poetry config virtualenvs.in-project true
	poetry config virtualenvs.prefer-active-python true
	poetry install

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	.venv/bin/pre-commit run --all-files

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	poetry run pytest -k "not slow"

test-full: ## Run all tests
		poetry run isort .
		poetry run black .
		poetry run pflake8 .
		poetry run mypy .
		poetry run pytest

train: ## Train the model
	python src/train.py
